name: Build and Commit

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Remove old build file
        run: |
          if [ -f build.tar.gz ]; then
            rm build.tar.gz
          fi

      - name: Install dependencies and build
        run: |
          yarn install
          yarn build

      - name: Create tar.gz of build
        run: tar -czf build.tar.gz build/

      - name: Commit and push changes
        run: |
          tar -xzf build.tar.gz -C ./
          git add .
          git commit -m "build on actions $(date +'%Y-%m-%d')"
          git push
